POST https://graphql.contentful.com/content/v1/spaces/toq4428iudhc/
Content-Type: application/json
Authorization: Bearer SJzuxAWAyxFy-15hC9-LzXgtN3ZqUd8rYlgdhcfCIug
X-REQUEST-TYPE: GraphQL

{
    pageCollection(where: {
        sys: {
          id_in: ["5KZkrAFUascF20azckCisu"]
      }
    }) {
        items {
            sys {
              id
              publishedAt
            }
            title
            information
            image {url}
    }
  }
}

###