name: storage_repository
description: Dart package which manages file CRUD operations.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.7
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+8

dev_dependencies:
  flutter_test:
    sdk: flutter
